name: Publish Package to npmjs
on:
  push:
    tags:        
      - v*.*.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish || true
      - run: sed 's/create-slimplate/slimplate/g' -i package.json
      - run: npm publish || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}